### ISSUE TITLE
`allOf` is not take in account correctly

### ISSUE THREAD

**Issue by sbrunner** [sbrunner/jsonschema-gentypes#8]
It is thread as `Union` but it should be an intersection.

See also: https://github.com/python/typing/issues/213

**Comment by Andrew-Chen-Wang** [comment]
I believe we can add a workaround for allOf to be compliant with type checkers.

Ref: https://github.com/python/typing/issues/213#issuecomment-217468239 The problem with intersection is in the broad sense, but because allOf is just finding the intersection with several schemas/classes, then you can simply implement an intersection type for generated schemas via:

```python
class _Intersection:
    def __getitem__(self, bases):
        full_bases = bases+(Protocol,)
        class Inter(*full_bases): ...
        return Inter

Intersection = _Intersection()
```
Ref: https://github.com/python/typing/issues/213#issuecomment-217465001

The other option is to use Protocols, which will help with autocompletion as well. Please let me know if I'm missing some points.
